version: '3'
services:
  nest-learn-api:
    image: ghcr.io/alexandr799/nest-work:develop
    container_name: nest-learn-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env